### ISSUE TITLE
More aliases for some countries

### ISSUE THREAD

**Issue by semio** [semio/ddf--gapminder--geo_entity_domain#1]
keys: the geo id used in this dataset.
values: the names for the geo id not in this dataset but used by other datasets.

The list may contain errors, need to double check.

``` yaml
irn:
    - Iran (Islamic Republic of)
irl:
    - Republic of Ireland
kor:
    - Republic of Korea
lao:
    - Lao People's Democratic Republic
ant:
    - Netherlands Antilles (former)
    - NETHERLAND ANTILLES AND ARUBA
sdn:
    - Sudan (former)
twn:
    - China, Taiwan Province of
yug:
    - Yugoslav SFR
    - YUGOSLAVIA MONTENEGRO SERBIA
tza:
    - United Republic of Tanzania
cod:
    - Democratic Republic of the Congo
cog:
    - Rep. of Congo (Brazzaville)
deu_west:
    - FEDERAL REPUBLIC OF GERMANY
deu_east:
    - FORMER GERMAN DEMOCRATIC REPUBLIC
fsm:
    - FEDERATED STATES OF MICRONESIA
yem_south:
    - FORMER DEMOCRATIC YEMEN
yem:
    - FORMER YEMEN
hkg:
    - HONG KONG SPECIAL ADMINSTRATIVE REGION OF CHINA
    - China Hong Kong SAR
    - China (Hong Kong SAR)
mac:
    - MACAU SPECIAL ADMINSTRATIVE REGION OF CHINA
    - China (Macao SAR)
    - macao, China
plw:
    - PACIFIC ISLANDS PALAU
mda:
    - REPUBLIC OF MOLDOVA
tca:
    - TURKS AND CAICOS ISLANDS
ussr:
    - USSR
wlf:
    - WALLIS AND FUTUNA ISLANDS
mkd:
    - YUGOSLAVIA FORMER SOCIALIST FEDERAL REPUBLIC
    - Macedonia (Former Yugoslav Republic of)
ngokar:
    - Nagorno-Karabakh
pyf:
    - Polynesia
vnm:
    - VietNam
dom:
    - Dominican rep.
cze:
    - Czech rep.
caf: 
    - Central African rep.
```
